/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119453-g37064b2d16-20250509"
#endif /* AVUTIL_FFVERSION_H */
